### ISSUE TITLE
[Bug]: K8s secret `vault-operator-creds` is not documented

### ISSUE THREAD

**Issue by cypherfox** [finleap-connect/vaultoperator#11]
**Describe the bug**
When deploying the vault operator, it references a K8s secret called `vault-operator-creds`.  The origins of it are not documented

From the name, I assume that it is used to authenticate the operator itself to the Vault.

Could you please document its purpose. Possibly with a rough sketch how to set it up. 
Ideally with a little script on how to roll out the required app-roles in Vault itself.

TIA

**Comment by jastBytes** [comment]
Hi @cypherfox! Thanks for reporting. You're totally right. The secret is expected to hold two fields to access Vault:
- VAULT_ROLE_ID
- VAULT_SECRET_ID

My suggestion is to make the secret name configurable via the values file and document this.
